language: android
sudo: false
cache: false
jdk: oraclejdk8
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    # Extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    # Emulator
    - sys-img-x86-android-29
    
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'

before_script:
    - chmod +x gradlew

script:
   - chmod +x ./gradlew
   - ./gradlew ktlintCheck
   - ./gradlew assembleDebug assembleRelease
   - ./gradlew test
